server:
  port: 8080
spring:
  application:
    name: acs_backend
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/dc?useSSL=FALSE&serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
      username: root
      password: 88888888
mybatis:
  type-aliases-package: edu.njucm._509
  mapper-locations: classpath:/impl/**/*.xml
logging:
  level:
    root: debug
